apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartservice
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
      annotations: # CONSUL
        #consul.hashicorp.com/connect-inject: 'true' # CONSUL
    spec:
      serviceAccountName: cartservice
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/cartservice:v0.8.0
        ports:
        - containerPort: 7070
        env:
        - name: REDIS_ADDR
          #value: "redis-cart:6379"
          value: "localhost:6379" # CONSUL

---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
  - protocol: TCP
    port: 7070
    targetPort: 7070
---
