---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations: # CONSUL
        consul.hashicorp.com/connect-inject: 'true' # CONSUL
        consul.hashicorp.com/transparent-proxy: 'false' # CONSUL
        consul.hashicorp.com/connect-service-upstreams: 'productcatalogservice:3550, currencyservice:7000, cartservice:7070, recommendationservice:8080, shippingservice:50052, checkoutservice:5050, adservice:9555' # CONSUL
    spec:
      serviceAccountName: frontend
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/frontend:v0.8.0
          ports:
          - containerPort: 8000
          env:
          - name: PORT
            value: "8000"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "localhost:3550" # CONSUL
            #value: "productcatalogservice:3550"
          - name: CURRENCY_SERVICE_ADDR
            value: "localhost:7000" # CONSUL
            #value: "currencyservice:7000"
          - name: CART_SERVICE_ADDR
            value: "localhost:7070" # CONSUL
            #value: "cartservice:7070"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "localhost:8080" # CONSUL
            #value: "recommendationservice:8080"
          - name: SHIPPING_SERVICE_ADDR
            value: "localhost:50052" # CONSUL
            #value: "shippingservice:50052"
          - name: CHECKOUT_SERVICE_ADDR
            value: "localhost:5050" # CONSUL
            #value: "checkoutservice:5050"
          - name: AD_SERVICE_ADDR
            value: "localhost:9555" # CONSUL
            #value: "adservice:9555"
          - name: DISABLE_PROFILER
            value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
---
