---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: redis-cart
# Allow traffic from cartservice to redis-cart
spec:
  destination:
    name: redis-cart
  sources:
    - name: cartservice
      action: allow
---
