apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: default
spec:
  services:
    - name: "shippingservice"
      consumers:
        - peer: "eks"
    - name: "paymentservice"
      consumers:
        - peer: "eks"
