apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: allowall
# Allow traffic from All Services to All Services
spec:
  destination:
    name: '*'
  sources:
    - name: '*'
      action: allow
